---
title: "workshop3"
author: "Khoi Tran"
date: "11/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#Command + Option + I = Generate R chunk (Ctrl+Alt+I)
library(tidyverse)
library(skimr)

#Import data source with "read" and "write" function
survey <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv')

#write_csv(survey,file = "survey_data.csv")
write_csv(survey,"survey_data.csv")


survey%>%glimpse()
survey%>%skim()
```
### Data WRANGLING

#### Filer

```{r}
#"==" Logical equal means the condition must always True
#"|" means OR
survey%>%
  filter(country=="Australia")
           
survey_IT_au<-survey%>%
  filter(country=="Australia" | country=="australia" | country=="Australi")%>%
  filter(industry=="Computing or Tech" & annual_salary>80000)
```
survey%>%
  filter(gender!="Man")

### Select

```{r}
survey_IT_au %>% 
  select(how_old_are_you, job_title, annual_salary)%>%
  arrange(desc(annual_salary))

survey%>%
 count(industry, gender, sort=TRUE)


survey%>%
  distinct(industry)

survey_IT_au %>%
  select(-industry)  

survey_IT_au%>%
  count(gender, city, sort=TRUE)

survey_IT_au%>%
  count(highest_level_of_education_completed, sort = TRUE)

survey_IT_au%>%
  add_count(highest_level_of_education_completed, sort = TRUE)
```

### `Mutate` vs `Transmute`

```{r}

class(survey_IT_au$annual_salary)
class(survey_IT_au$other_monetary_comp)

survey_IT_au%>%
  mutate(total_salary=annual_salary+other_monetary_comp)

survey_IT_au<-survey_IT_au%>%
  mutate(avr_salary=mean(annual_salary))

survey_IT_au%>%
  count(city)

survey_IT_au_grouped<-survey_IT_au%>%
  group_by(city)%>%
  mutate(max_salary=max(annual_salary))%>%
  ungroup()



survey_IT_au_grouped<-survey_IT_au%>%
  group_by(city)%>%
  mutate(max_salary=max(annual_salary))%>%
  select(how_old_are_you, job_title, city, annual_salary, avr_salary, max_salary)


survey_IT_au%>%
  group_by(gender,city)%>%
  summarise(min_salary=min(annual_salary),
            max_salary=max(annual_salary),
            avr_salary=mean(annual_salary))%>%
  arrange(desc(avr_salary))%>%
  ungroup()


survey_IT_au<-survey_IT_au%>%
  mutate(age=parse_number(how_old_are_you))

survey_IT_au%>%
  mutate(condition = case_when(job_title == "Business Analyst" ~ "yes", T ~ "no"))
  
survey_IT_au<-survey_IT_au%>%
  mutate(age=parse_number(overall_years_of_professional_experience))


```
## Data Visualization

### Cleaning data
```{r}
survey <- survey %>%
  mutate(timestamp = mdy_hms(timestamp),
         age_category = fct_relevel(fct_reorder(how_old_are_you, parse_number(how_old_are_you)), "under 18"),
         experience_overall = str_replace(overall_years_of_professional_experience, " - ", "-"),
         experience_overall = fct_reorder(experience_overall, parse_number(experience_overall)),
         experience_in_field = str_replace(years_of_experience_in_field, " - ", "-"),
         experience_in_field = fct_reorder(experience_in_field, parse_number(experience_in_field))) %>%
  mutate(gender = fct_collapse(coalesce(gender, "Other or prefer not to answer"), "Other or prefer not to answer" = c("Other or prefer not to answer", "Prefer not to answer")),
         race = fct_lump(coalesce(race, "Other"), 4),
         age=parse_number(how_old_are_you))

survey_usd <- survey %>%
  filter(currency == "USD") %>%
  filter(annual_salary >= 5000,
         annual_salary <= 2e6) %>%
  mutate(state = str_remove(state, ", .*"))

```






